title: Game Dev Blog
author: FuJiGraphics
email: chlcjfwls1@naver.com
description: >-
  Game Dev Blog
baseurl: ""
url: "https://FuJiGraphics.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate-v2 # v2로 변경
plugins_dir: ./_plugins
    
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class : 'syntax'

# V2용 페이지네이션 설정
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  index_page_name: 'index.html'
  sort_reverse: true

autopages:
  enabled: true
  tags:
    enabled: true
    layouts: 
      - archive.html  # 반드시 확장자 포함
    permalink: '/tag/:tag/' # 윈도우 폴더 생성 오류 방지
  categories:
    enabled: false
  collections:
    enabled: false

timezone: Asia/Seoul
google_analytics: G-D4BH33MKK3